name: Github WorkFlow

on:
  workflow_dispatch:

jobs:
  setup-vps:
    runs-on: ubuntu-latest 

    steps:
      - name: Install SSH and Set Password
        run: |
          sudo apt update && sudo apt install -y openssh-server curl
          sudo service ssh start

          # Set a password for the 'runner' user
          echo "runner:MySecurePass123" | sudo chpasswd

          # Allow password authentication in SSH
          sudo sed -i 's/^#PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Display SSH Connection Info
        run: |
          echo "SSH is running on port 22"
          echo "Connect using: ssh runner@$(curl -s ifconfig.me) -p 22"
          echo "Password: MySecurePass123"

      - name: Keep Runner Alive
        run: sleep infinity
